var emojis1 = [
    'grinning',
    'joy',
    'smiley',
    'sweat_smile',
    'wink',
    'sweat_smile',
    'laughing',
    'yum',
    'sunglasses',
    'rage',
    'confounded',
    'flushed',
    'disappointed',
    'sob',
    'neutral_face',
    'innocent',
    'grin',
    'smirk',
    'scream',
    'sleeping',
    'flushed',
    'confused',
    'mask',
    'blush',
];
var emojis2 =[
    'innocent',
    'smiling_imp',
    'kissing_heart',
    'stuck_out_tongue_closed_eyes',
    'triumph',
    'face_with_rolling_eyes',
    'worried',
    'hushed',
    'heartbeat',
    'broken_heart',
    'crescent_moon',
    'star2',
    'sunny',
    'rainbow',
    'heart_eyes',
    'raised_hands',
    'see_no_evil',
    'no_good',
    'ok_woman',
    'kissing_smiling_eyes',
    'rose',
    'pray',
    'rocket',
    '+1',
]
var emojis = {
    "1": emojis1,
    "2": emojis2 
}
export default emojis;
